### ISSUE TITLE
Install GIT

### ISSUE THREAD

**Issue by odv** [js-mentorship/git#1]
Install GIT: https://git-scm.com/download/win

Note: You don't need to change any settings at this point when installing. Stick with the default instalation options.

After you've installed it, run **Git Bash**, take a screenshot, drag it in the comment box and assign the ticket back to me.

'Git Bash' is an interface through which you interact with GIT.

**Comment by RazvanBugoi** [comment]
![screenshot_1](https://user-images.githubusercontent.com/46108577/50487535-aec10180-09f6-11e9-9bf7-cf391ae43aac.jpg)
