### ISSUE TITLE
First-Time Git Configuration

### ISSUE THREAD

**Issue by odv** [js-mentorship/git#2]
Since this is the first time when you'll use GIT on your system, you need to do some basic configurations.

https://git-scm.com/book/en/v2/Getting-Started-First-Time-Git-Setup

Note: At this point, the only section that is useful for you is **Your Identity*.  Paste a screenshot of your Git Bash, after you've configured it, here, and assign the ticket back to me.

**Comment by RazvanBugoi** [comment]
![screenshot_2](https://user-images.githubusercontent.com/46108577/50487745-5c341500-09f7-11e9-9ab0-0bdcff3beaee.jpg)

**Comment by odv** [comment]
@RazvanBugoi Remember to unasign yourself(top right corner) and assign that issue back to me when you want me to review/close it.

**Comment by RazvanBugoi** [comment]
@odv  I closed it and opened it again, is that what you mean by unassign myself? 

![screenshot_3](https://user-images.githubusercontent.com/46108577/50488479-ae2a6a00-09fa-11e9-82f3-b2556d3e0346.jpg)

**Comment by odv** [comment]
![github](https://user-images.githubusercontent.com/5067625/50489375-00c25100-0a10-11e9-8365-bdc2e3c3dfed.png)

@RazvanBugoi Click on the gearbox icon, click on my username until you can see a 'checkmark' symbol  before my username and click on your username in order to remove that 'checkmark' symbol. This is how you unasign yourself.

**Comment by odv** [comment]
@RazvanBugoi  It seems like you can't no longer unassign yourself if you're not the creator. 
Well done, I will close this one.
