### ISSUE TITLE
Generate SSH key and add it to Github

### ISSUE THREAD

**Issue by odv** [js-mentorship/git#3]
Follow only the **Generating a new SSH key** section.

https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/#generating-a-new-ssh-key

Note: At this point, you can simply press ENTER two times/confirmation when prompted for a passphrase. You don't need a SSH passphrase now.

Paste a screenshot of your Git Bash after you've successfully completed this step.

**Comment by RazvanBugoi** [comment]
![screenshot_5](https://user-images.githubusercontent.com/46108577/50490250-f8fcaf80-0a03-11e9-9574-149fd1c214de.jpg)
