### ISSUE TITLE
Create a 'README.md' file

### ISSUE THREAD

**Issue by odv** [js-mentorship/git#5]
Create a 'README.md' file and store your notes on GIT.

If you want to use markdown to improve the readability of your document, have a look over this link:  https://guides.github.com/features/mastering-markdown/

You can read more about README files here: https://en.wikipedia.org/wiki/README

The reason we're creating this type of file is that, later, thanks to Github, you can quickly refer to your notes in a quick and neat way.

**Comment by odv** [comment]
@RazvanBugoi  Some additional screenshots to aid you in the process of creating this README file.

![step1](https://user-images.githubusercontent.com/5067625/50489775-4b44cd00-0a12-11e9-92bd-74ffe41946f0.png)

![step2](https://user-images.githubusercontent.com/5067625/50489779-4e3fbd80-0a12-11e9-9f36-1e5f48a50ff8.png)

![step3](https://user-images.githubusercontent.com/5067625/50489784-55ff6200-0a12-11e9-95ee-ba5df1fa19f4.png)

**Comment by RazvanBugoi** [comment]
![screenshot_1](https://user-images.githubusercontent.com/46108577/50518908-269f3280-0ab0-11e9-94b0-a9d9fb93a45d.jpg)
