### ISSUE TITLE
Add the basic Git commands to your README.md file

### ISSUE THREAD

**Issue by odv** [js-mentorship/git#6]
Add the basic commands that I've told you today about to your notes.

**Comment by RazvanBugoi** [comment]
![screenshot_1](https://user-images.githubusercontent.com/46108577/50525254-3cbdea80-0ad2-11e9-8aa1-f684563fb8bf.jpg)

**Comment by odv** [comment]
@RazvanBugoi There are a few changes that you need to make:

1| Here you're not cloning the ssh key, you're cloning the repository which is the remote folder where you've stored your code. The ssh key is used only for proving your identity. This is why you added your SSH key in Github so that later when you clone from Git Bash, you can prove your identity and clone/change that repository.

5| You can rephrase it like in the official documentation, "Show the working tree status".

8| Using this command you record changes to the repository(remember when we talk yesterday about that 'long order number', files changed after you've executed this comand?) and add a commit message by using the -m flag. You need to rephrase it as at this stage, your files are not transmited to Github or any other similar site yet. The changes are still local at this point.

9| While you are not wrong, it is better to rephrase it generally.  Something like "Update remote reference". The reason for this is that there are multiple services like Github. For example Bitbucket, Gitlab, etc. So remote reference can mean any repository from any service.


After you've finished improving the notes, based on the points above, push the file so we can see the changes on Github. Well done!

**Comment by RazvanBugoi** [comment]
![screenshot_2](https://user-images.githubusercontent.com/46108577/50539470-b1e3fb00-0b78-11e9-9258-61cae37f0962.jpg)

**Comment by RazvanBugoi** [comment]
File has been modified and pushed to remote repository.
